# Generated by Django 2.1.7 on 2019-03-24 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_noticias', '0003_auto_20190322_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64)),
                ('slug', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='noticia',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_noticias.Pessoa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone_celular',
            field=models.CharField(blank=True, help_text='Numero de telefone celular no formato (99)99999-9999', max_length=15, null=True, verbose_name='Telefone Celular'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone_fixo',
            field=models.CharField(blank=True, help_text='Numero de telefone Fixo no formato (99)99999-9999', max_length=15, null=True, verbose_name='Telefone Fixo'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Cpf'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='dataNascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='tags',
            field=models.ManyToManyField(to='app_noticias.Tag'),
        ),
    ]
